<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.2 (Python 3.9.0 on win32)" generated="20210707 15:25:20.857" rpa="false" schemaversion="2">
<suite id="s1" name="Mysqldb" source="D:\COE_Automation\Database\Mysqldb.robot">
<kw name="Connect To Database" library="DatabaseLibrary" type="SETUP">
<arg>pymysql</arg>
<arg>${dbname}</arg>
<arg>${dbuser}</arg>
<arg>${dbpass}</arg>
<arg>${dbhost}</arg>
<arg>${dbport}</arg>
<doc>Loads the DB API 2.0 module given `dbapiModuleName` then uses it to
connect to the database using `dbName`, `dbUsername`, and `dbPassword`.</doc>
<msg timestamp="20210707 15:25:21.870" level="INFO">Connecting using : pymysql.connect(db=robot, user=root, passwd=, host=localhost, port=3306, charset=None) </msg>
<status status="PASS" starttime="20210707 15:25:21.837" endtime="20210707 15:25:21.881"/>
</kw>
<test id="s1-t1" name="TC1 Databse Connection">
<kw name="Run Keyword And Ignore Error" library="BuiltIn">
<var>${status}</var>
<var>${checking}</var>
<arg>Comparing</arg>
<doc>Runs the given keyword with the given arguments and ignores possible error.</doc>
<kw name="Comparing">
<kw name="Check If Not Exists In Database" library="DatabaseLibrary">
<arg>SELECT * FROM apidetails WHERE API_Name = '${API_to_run}';</arg>
<doc>This is the negation of `check_if_exists_in_database`.</doc>
<msg timestamp="20210707 15:25:21.884" level="INFO">Executing : Check If Not Exists In Database  |  SELECT * FROM apidetails WHERE API_Name = 'TestAPI'; </msg>
<msg timestamp="20210707 15:25:21.884" level="INFO">Executing : Query  |  SELECT * FROM apidetails WHERE API_Name = 'TestAPI'; </msg>
<msg timestamp="20210707 15:25:21.888" level="FAIL">Expected to have have no rows from 'SELECT * FROM apidetails WHERE API_Name = 'TestAPI';' but got some rows : (('TestAPI', 'GET', 'https', 'reqres.in', '/api/users/$2$', '{"":""}', '{"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "Referer": "https://reqres.in/", "Connection": "keep-alive", "Upgrade-Insecure-Requests": "1"}', '{"":""}', 'D:/Programming/Application Security/coe-application-security/DataFiles/Payloads.xlsx', 'SQL'),).</msg>
<status status="FAIL" starttime="20210707 15:25:21.884" endtime="20210707 15:25:21.889"/>
</kw>
<status status="FAIL" starttime="20210707 15:25:21.883" endtime="20210707 15:25:21.889"/>
</kw>
<msg timestamp="20210707 15:25:21.889" level="INFO">${status} = FAIL</msg>
<msg timestamp="20210707 15:25:21.889" level="INFO">${checking} = Expected to have have no rows from 'SELECT * FROM apidetails WHERE API_Name = 'TestAPI';' but got some rows : (('TestAPI', 'GET', 'https', 'reqres.in', '/api/users/$2$', '{"":""}', '{"Accept": "text/h...</msg>
<status status="PASS" starttime="20210707 15:25:21.883" endtime="20210707 15:25:21.889"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${API_to_run}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20210707 15:25:21.890" endtime="20210707 15:25:21.890"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>${status}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20210707 15:25:21.891" endtime="20210707 15:25:21.892"/>
</kw>
<kw name="Run Keyword If" library="BuiltIn">
<arg>'${status}' =='PASS'</arg>
<arg>Insert API</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<status status="PASS" starttime="20210707 15:25:21.892" endtime="20210707 15:25:21.893"/>
</kw>
<tag>database_connection</tag>
<status status="PASS" starttime="20210707 15:25:21.882" endtime="20210707 15:25:21.893"/>
</test>
<status status="PASS" starttime="20210707 15:25:20.878" endtime="20210707 15:25:21.895"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="1" fail="0" skip="0">database_connection</stat>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Mysqldb">Mysqldb</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210707 15:25:20.951" level="ERROR">Error in file 'D:\COE_Automation\Resources\API.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\Scripts\robot.exe
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39
  c:\users\palak.vora\appdata\local\programs\python\python39\python39.zip
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib
  C:\Users\palak.vora\AppData\Roaming\Python\Python39\site-packages
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib\site-packages</msg>
<msg timestamp="20210707 15:25:20.954" level="ERROR">Error in file 'D:\COE_Automation\Resources\API.robot' on line 3: Importing library 'JSpringBotGlobal' failed: ModuleNotFoundError: No module named 'JSpringBotGlobal'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\Scripts\robot.exe
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39
  c:\users\palak.vora\appdata\local\programs\python\python39\python39.zip
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib
  C:\Users\palak.vora\AppData\Roaming\Python\Python39\site-packages
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib\site-packages</msg>
<msg timestamp="20210707 15:25:21.168" level="ERROR">Error in file 'D:\COE_Automation\Resources\API.robot' on line 6: Importing library 'JSONLibrary' failed: ModuleNotFoundError: No module named 'JSONLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\Scripts\robot.exe
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39
  c:\users\palak.vora\appdata\local\programs\python\python39\python39.zip
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib
  C:\Users\palak.vora\AppData\Roaming\Python\Python39\site-packages
  C:\Users\palak.vora\AppData\Local\Programs\Python\Python39\lib\site-packages</msg>
</errors>
</robot>
